넘파이(Numpy)  라이브러리
- 대용량 배열과 행렬연산에 대한 고속연산을 지원하는 라이브러리
- 딥러닝에 입력으로 들어가는 이미지 , 4차원 데이터 (batch_size, 높이 ,너비, 채널 수) 

플라틀

플라틀(FLAT)은 다차원 배열의 데이터를 1차원으로 평탄화(flattening)하는 기능을 제공하는 메서드입니다. 
이를 통해 다차원 배열을 1차원 배열로 변환할 수 있습니다.  


<기타, 명령어모음 > -- 가상환경 구축 
- 아나콘다 에서 최신버전으로 update 
 	1) anaconda prompt 관리자모드실행 -> conda update -n base conda
	   ( Conda 패키지 관리자를 업데이트하는 명령어 ) 
	2) conda update --all  
	   ( Conda 환경에 설치된 패키지들을 최신 버전으로 업데이트)
	3)conda --version
	   ( conda 현재 버전확인)
	4)conda list
	   ( conda 가상환경에 설치된 패키지들, 라이브러리의 목록을 보여주는 명령어, )
	5)conda create --name CW_AI_Academy 
	   ( conda 환경에서 새로운 가상환경을 생성)
	6)conda activate CW_AI_Academy
	   ( CW_AI_Academy를 활성화시킨다 , 이러면 프롬프트입력줄 앞에 이름달림) 
	7)conda install numpy
	   (  패키지 매니저를 사용하여 지정한 패키지를 설치하는 명령어 )  

In [2]:
import numpy as np 
import time

In [18]:
#배열을 이용한 시간찾기
start_time = time.time()
numbers = range(1,1000001)
squares = []
for num in numbers:
    squares.append(num**2)
end_time = time.time()
print(end_time-start_time)

#numpy를 이용한 시간찾기
#속도차이 많이남 
start_time = time.time()
numbers = np.arange(1,1000001)
squares = np.square(numbers)

end_time = time.time()
print(end_time-start_time)

0.09629201889038086
0.006675004959106445


In [1]:
#Numpy 배열생성 
#행이 하나인 배열 만들기 
arr = np.array([1,2,3,4,5]) #배열로 넣기  
arr2 = np.array((1,2,3,4,5))#튜플로 넣기
print(type(arr))
print(type(arr2))

#★★★★★
print("arr의 형태 : ",arr.shape) #★배열의 형태  -> 5, 콤마뒤에 아무것도 없기에 1차윈 ex) 5,6 2차원 5,7,1 3차원
print("arr의 차원수 : ",arr.ndim)#★배열의 차원수
print("arr의 내부 원소의 자료형 : ",arr.dtype)#★배열 내부 원소의 자료형

print("arr의 내부 원소의 크기 : ",arr.itemsize)#배열 내부 원소의 크기 (바이트 단위)
print("arr의 내부 원소의 개수 : ",arr.size)#배열 내부 원소의 개수 
 #arr.shape 뒤에있는 shape 도 멤버변수임 이유: 뒤에 괄호() 가없기 떄문  

arr_2d = np.array([[np.arange(3),np.arange(3)],[np.arange(3),np.arange(3)]])  #안쓰는방법이지만 가능  일정한배열로생성 
# print(arr_2d) 
arr_2d = np.array([[np.arange(1,10).reshape(3,3)],[np.arange(1,10).reshape(3,3)]]) 
# print(arr_2d)


#Numpy 배열생성 
#열이 하나인 배열 만들기  
arr = np.array([[1],[2],[3],[4],[5]])  

print("arr의 형태 : ",arr.shape) #배열의 형태  -> 5,1  -> 5행 1열 (2차원)  각차원의 길이 
print("arr의 차원수 : ",arr.ndim)#대괄호 갯수를 보고 차원수 짐작가능  
print("arr의 내부 원소의 자료형 : ",arr.dtype) 
print("arr의 내부 원소의 크기 : ",arr.itemsize)
print("arr의 내부 원소의 개수 : ",arr.size)

NameError: name 'np' is not defined

In [3]:
#Numpy 에서 차원의 의미 
    #1차원 배열은 하나의 축으로 이루어진 배열 : (5,) -> 튜플임 
    #2차원 배열은 두개의 축으로 이루어진 배열 : (2,3)
    #3차원 배열은 세개의 축으로 이루어진 배열 : (4,3,2)
    #4차원 배열은 네개의 축으로 이루어진 배열 : (2,4,5,2)

    
#배열을 그냥 만들면 에러 떠서 0으로 만들려면 이렇게 해야함
#디폴트로 요소의 값은 모두 실수형으로 채워짐 
arr_zeros = np.zeros(3)
print(arr_zeros)

#dtype옵션을 이용해 요소의 형을 지정 
arr_zeros = np.zeros((5,2),dtype=int) 
print(arr_zeros)

#2행 3열 의 2차원배열 2개 존재하는 3차원 배열 (depth 2  , 2행 , 3열)
arr_ones = np.zeros((2,2,3),dtype=str) 
print(arr_ones)

#Empty  -> 쓰레기 값 (garbage value)가들어갈수있음
arr_empty = np.empty((2,3))
print(arr_empty)

#full(a,b) -> a안에  b로 다넣어준다
arr_full = np.full((2,3,3),5)
print(arr_full)

#arange() -> 지정된 범위내에서 지정된 간격으로 일정한 값의 배열을 생성 #나중에 reshape 이란 함수랑 같이 쓰임
arr_arange_01 = np.arange(10)   #1차원 배열만 생성이됨                 # (3,3) 을 10 개로 넣을수없을때 다시 모양만들어줘야함 
print(arr_arange_01)                                                   #  ex)(2,5)(5,2)(1,10)(10,1)

#reshape()
arr_arange_02 = np.arange(10).reshape(2,5)
print(arr_arange_02)

#linspace() 지정된 범위에서 지정된 개수만큼 동일한 간격으로 일정한 값의 배열을 생성
arr_linspace_01 = np.linspace(0,1,5) #  linspace(시작값(start),범위의 끝값(stop),생성할 값의 개수(num))
print(arr_linspace_01)

#randint  
q = np.random.randint(0,9,size=(5)) # randint(랜덤한숫자 0~ 9 , size = 몇개)
print(q)

#a.tolist() #a 라는 numpy list 를 일반 list로 형변환 , 1차원 배열인경우 그냥 list 쒸우면되지만 2차원이상은 tolist 써줘야함
a = np.ones([5,5])
a=a.tolist()
print(type(a))

[0. 0. 0.]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[['' '' '']
  ['' '' '']]

 [['' '' '']
  ['' '' '']]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]]
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0.   0.25 0.5  0.75 1.  ]
[6 1 6 5 7]
<class 'list'>


In [58]:
#넘파이보다 더 강력한게 Broadcasting 
arr = np.array([[[1],[2]],
                [[3],[4]],
                [[5],[6]]])   
print(arr+10) # v1 배열에 모두다 10을 더해줌 ! 

print(arr + np.array([10,100,1000])) # 각각의 행에다가 똑같은 길이의 백터를 더해줌 

v1 = np.array([[1,2,3],[4,5,6]])
v2 = np.array([[2,7,6],[1,0,6]])  

print(v1 > v2)    #배열 비교

print(v1 != 3)  #3이 아닌것

print(v1%2==0)  # 짝수 홀수 찾기 

[[[11]
  [12]]

 [[13]
  [14]]

 [[15]
  [16]]]
[[[  11  101 1001]
  [  12  102 1002]]

 [[  13  103 1003]
  [  14  104 1004]]

 [[  15  105 1005]
  [  16  106 1006]]]
[[False False False]
 [ True  True False]]
[[ True  True False]
 [ True  True  True]]
[[False  True False]
 [ True False  True]]


In [3]:
#nunpy의 기본 indexing과 Slicing 
v1 = np.array([[1,2,3],[4,5,6]])
v2 = np.array([[2,7,6],[1,0,6]])

print(np.array([1,2,3])[1],"\n")
print(v1[1][1],"\n") #인덱싱                                          #★인덱실할때 차원이 줄어듬 
print(v1[0:1,1:],"\n") #슬라이싱  v1의[0번열] , [1번열~]   -> 2,3   #★슬라이싱하면 차원이 그대로 ! 
print(v1[1:2,:2]) 



2 

5 

[[2 3]] 

[[4 5]]


In [344]:
#할당하는법
v1 = np.array([[1,2,3],[4,5,6]])
v1[0] =  0

print(v1)  #1번열 모든 행 0으로 할당

v1[1][2]=1 #2번째열 3번째를 1로 할당
print(v1)

v1[:] =0   #모든열,행 0으로 할당
print(v1) 

v1+=5     #a모든열,행 5 더해줌 
print(v1)

v1 = np.array([[1,2,3],[4,5,6]])
v1[0]=([0,1,2]) #1번쨰열 0 , 1 ,2 로 바꾸기 
print(v1)

v1[:]=[100],[200] #1번째 열 모든행 100 2번째열 모든행 200 
print(v1)


[[0 0 0]
 [4 5 6]]
[[0 0 0]
 [4 5 1]]
[[0 0 0]
 [0 0 0]]
[[5 5 5]
 [5 5 5]]
[[0 1 2]
 [4 5 6]]
[[100 100 100]
 [200 200 200]]


In [149]:
#4차원 
z1=np.zeros((2,3,4,5)) #요소 5개 있는 4개있는 3개의 2개 
                    #2개안에 3개가 있는데 그 3개안에 4개 그 4개안에 5개가있음 

# z1[0,2,2] =1
print(z1)
print("\n\n====================\n\n")
z1[0,:,:,1]=1 
z1[0,1:]=1 #만약에 하위차원이 전체면 안적어도됨 
               # z1[0,1:,:,:]=1   와 z1[0,1:]=1 같음  
print(z1[0])

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]




[[[0. 1. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 1. 0. 0. 0.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [351]:
#fancy 인덱싱, fancy 슬라이싱

v1= np.array([[1,2,3],[4,5,6]])

print(v1[:,[0,2]],"\n")  #배열 중간거를 없앨수있음!( 빼고 출력할수있음 )


z= np.linspace(1,120,120).reshape((2,3,4,5))  # 1~120 까지 120 번으로 나눈걸넣으면 1~120 씩 정수들어감 이걸 4차원(2,3,4,5)로 리쉡
print(z)

print(z[0,1,:,[0,1,3,4]],"\n")  #제일큰 2개중 1번째 있는거에 , 2번째있는  , 전부 , 0,1,3,4에있는 것들 
print(z[0, 1, :, np.concatenate([np.arange(0, 2), np.arange(3, 5)])],"\n")  #방법2


[[1 3]
 [4 6]] 

[[[[  1.   2.   3.   4.   5.]
   [  6.   7.   8.   9.  10.]
   [ 11.  12.  13.  14.  15.]
   [ 16.  17.  18.  19.  20.]]

  [[ 21.  22.  23.  24.  25.]
   [ 26.  27.  28.  29.  30.]
   [ 31.  32.  33.  34.  35.]
   [ 36.  37.  38.  39.  40.]]

  [[ 41.  42.  43.  44.  45.]
   [ 46.  47.  48.  49.  50.]
   [ 51.  52.  53.  54.  55.]
   [ 56.  57.  58.  59.  60.]]]


 [[[ 61.  62.  63.  64.  65.]
   [ 66.  67.  68.  69.  70.]
   [ 71.  72.  73.  74.  75.]
   [ 76.  77.  78.  79.  80.]]

  [[ 81.  82.  83.  84.  85.]
   [ 86.  87.  88.  89.  90.]
   [ 91.  92.  93.  94.  95.]
   [ 96.  97.  98.  99. 100.]]

  [[101. 102. 103. 104. 105.]
   [106. 107. 108. 109. 110.]
   [111. 112. 113. 114. 115.]
   [116. 117. 118. 119. 120.]]]]
[[21. 26. 31. 36.]
 [22. 27. 32. 37.]
 [24. 29. 34. 39.]
 [25. 30. 35. 40.]] 

[[21. 26. 31. 36.]
 [22. 27. 32. 37.]
 [24. 29. 34. 39.]
 [25. 30. 35. 40.]] 



In [339]:
 #Boolean mask   
mask = v1%2 == 0  #배열안 원소값이 2 로 나눴을때 0 이면 0으로 할당
v1[mask] =0
print(v1,"\n")


arr=np.array([1,2,3,4,5,6])
mask=arr%2!=0
arr=arr[mask] 

print(arr)

[[1 0 3]
 [0 5 0]] 

[1 3 5]


In [28]:
arr1 = [1,2,3] + [2,7,10]
print(arr1)

arr1 = np.array([1,2,3])
arr2 = np.array([2,7,10])
print(arr1+arr2)

print(list(map(lambda x : x[0]+x[1], zip([1,2,3],[2,7,10]))))

v1=np.array([[1,2,3],[4,5,6],
            [2,7,10],[5,3,5]])
v2=np.array([[2,4,3],[2,7,10],
            [1,2,3],[2,6,5]])

print("\nv1-v2")
print(v1-v2 ,"\n")

print("\nv1/v2")
print(v1/v2 ,"\n")

print("\nv1%v2")
print(v1%v2 ,"\n")

print("\nv1+v2")
print(v1+v2 ,"\n")


print("\nv1**v2")
print(v1**v2 ,"\n")

[1, 2, 3, 2, 7, 10]
[ 3  9 13]
[3, 9, 13]

v1-v2
[[-1 -2  0]
 [ 2 -2 -4]
 [ 1  5  7]
 [ 3 -3  0]] 


v1/v2
[[0.5        0.5        1.        ]
 [2.         0.71428571 0.6       ]
 [2.         3.5        3.33333333]
 [2.5        0.5        1.        ]] 


v1%v2
[[1 2 0]
 [0 5 6]
 [0 1 1]
 [1 3 0]] 


v1+v2
[[ 3  6  6]
 [ 6 12 16]
 [ 3  9 13]
 [ 7  9 10]] 


v1**v2
[[       1       16       27]
 [      16    78125 60466176]
 [       2       49     1000]
 [      25      729     3125]] 



In [270]:
import numpy as np

#1번 문제 
a=np.zeros([3,3])
print(a,"<<1번 \n")

#2번 문제
q = np.random.randint(0,9,size=(5))
print(q,"<<2번 \n")

#3번 문제
b=np.full([2,3,4],1)
print(b,"<<3번 \n")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] <<1번 

[6 8 6 6 6] <<2번 

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] <<3번 



In [342]:
#q2 
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)         #크기 
print(arr.size)          #요소개수
print(arr.dtype)         #데이터 타잎 

#q3
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

#더하기
print(arr1+arr2)
#빼기
print(arr1-arr2)
#곱
print(arr1*arr2)
#나누기
print(arr1/arr2)
#첫번째 배열 제곱
print(arr1**2)
#두 배열 평균구하기 
print((arr1+arr2)/2)

(2, 3)
6
int32
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[2.5 3.5 4.5]


In [350]:
#4
a = np.ones([5,5])
a[:] = 5 
# a= a.tolist() # nested list 형변환
print(a,"\n")

#5
arr=np.array([1,2,3,4,5,6])
print(arr[arr%2!=0])
print(arr[[0,2,4]])

mask=arr%2!=0
arr=arr[mask] 
print(arr)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]] 

[1 3 5]
[1 3 5]
[1 3 5]


In [50]:
#예제 1  (3,3) 형태의 배열을 만들어라 (3행(3개) , 3열(3줄)) 
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print("arr의 형태 : ", arr.shape )  
print("arr의 차원수 : ", arr.ndim ) 
print("arr의 내부 원소의 자료형 : ", arr.dtype)

print("arr의 내부 원소의 크기 : ", arr.itemsize)
print("arr의 내부 원소의 개수 : ", arr.size)


arr의 형태 :  (3, 3)
arr의 차원수 :  2
arr의 내부 원소의 자료형 :  int32
arr의 내부 원소의 크기 :  4
arr의 내부 원소의 개수 :  9
